"""
Measurement Time Simulator - Фреймворк для симуляции времени измерения информации
в физических системах с учетом квантовых пределов, декогеренции и шума.
"""

from .constants import (
    HBAR,
    KB,
    DEFAULT_N_Q,
    DEFAULT_DELTA_E,
    DEFAULT_TAU_TECH,
    DEFAULT_T_STAR,
    MIN_TEMPERATURE,
    MIN_DELTA_E,
    DEFAULT_T1,
    DEFAULT_T2,
    MIN_T1,
    MIN_T2,
    DEFAULT_NOISE_TEMPERATURE,
    DEFAULT_SHOT_NOISE_FACTOR,
    DEFAULT_TECHNICAL_NOISE,
    DEFAULT_EQUILIBRIUM_TIME,
    MIN_EQUILIBRIUM_TIME,
    DEFAULT_DETECTOR_RESPONSE_TIME,
    MIN_DETECTOR_RESPONSE_TIME,
    DETECTOR_TIME_FERMION,
    DETECTOR_TIME_BOSON,
    DETECTOR_TIME_CLASSICAL,
    EQUILIBRIUM_TIME_FERMION,
    EQUILIBRIUM_TIME_BOSON,
    EQUILIBRIUM_TIME_CLASSICAL,
    EQUILIBRIUM_TIME_CORRELATED,
    DEFAULT_FLICKER_NOISE_FACTOR,
    DEFAULT_QUANTUM_NOISE_FACTOR,
    DEFAULT_ENVIRONMENT_NOISE_FACTOR,
    FERMION_COEFF,
    BOSON_COEFF,
    CORRELATION_COEFF,
    QUASIPARTICLE_COEFF,
    GAMMA_BASE_COEFF,
    N_LOG_DIVISOR,
    HAS_CUPY,
    HAS_NUMBA_CUDA,
)
from .particle_statistics import ParticleStatistics
from .exporter import ResultExporter
from .simulator import GPUInformationMeasurementSimulator
from .optimizations import get_optimized_calculator, OptimizedCalculator, HAS_NUMBA

__version__ = "0.1.0"
__author__ = "Measurement Time Simulator Team"

__all__ = [
    "ParticleStatistics",
    "ResultExporter",
    "GPUInformationMeasurementSimulator",
    "get_optimized_calculator",
    "OptimizedCalculator",
    "HAS_NUMBA",
    "HBAR",
    "KB",
    "DEFAULT_N_Q",
    "DEFAULT_DELTA_E",
    "DEFAULT_TAU_TECH",
    "DEFAULT_T_STAR",
    "MIN_TEMPERATURE",
    "MIN_DELTA_E",
    "DEFAULT_T1",
    "DEFAULT_T2",
    "MIN_T1",
    "MIN_T2",
    "DEFAULT_NOISE_TEMPERATURE",
    "DEFAULT_SHOT_NOISE_FACTOR",
    "DEFAULT_TECHNICAL_NOISE",
    "DEFAULT_EQUILIBRIUM_TIME",
    "MIN_EQUILIBRIUM_TIME",
    "DEFAULT_DETECTOR_RESPONSE_TIME",
    "MIN_DETECTOR_RESPONSE_TIME",
    "DETECTOR_TIME_FERMION",
    "DETECTOR_TIME_BOSON",
    "DETECTOR_TIME_CLASSICAL",
    "EQUILIBRIUM_TIME_FERMION",
    "EQUILIBRIUM_TIME_BOSON",
    "EQUILIBRIUM_TIME_CLASSICAL",
    "EQUILIBRIUM_TIME_CORRELATED",
    "DEFAULT_FLICKER_NOISE_FACTOR",
    "DEFAULT_QUANTUM_NOISE_FACTOR",
    "DEFAULT_ENVIRONMENT_NOISE_FACTOR",
    "FERMION_COEFF",
    "BOSON_COEFF",
    "CORRELATION_COEFF",
    "QUASIPARTICLE_COEFF",
    "GAMMA_BASE_COEFF",
    "N_LOG_DIVISOR",
    "HAS_CUPY",
    "HAS_NUMBA_CUDA",
]
